export const chatData = [
  {
    id: 1,
    name: "KerryAnne",
    chat: "I've recieved the money I am happy I love you",
    unreadMessages: 3,
    recentAmount: "15,000,000,000",
    recentCurrency: "XAF",
    time: "10:30AM",
    photo: require("../../images/Ker.jpg"),
    seen:true
  },
  {
    id: 2,
    name: "Oliver",
    chat: "Yesai Bro thanks for the dos. Je voulais te joss ",
    unreadMessages: 0,
    recentAmount: "1,000",
    recentCurrency: "USD",
    time: "1:05AM",
    photo: require("../../images/Oli.jpg"),
    seen:true

  },
  {
    id: 3,
    name: "Mondamwe",
    chat: "Send me that Stupid money bro",
    unreadMessages: 5,
    recentAmount: "100",
    recentCurrency: "USD",
    time: "5:25AM",
    photo: require("../../images/monda.jpg"),
    seen:true

  },
  {
    id: 4,
    name: "Agendiamwe",
    chat: "Boy I told you that Cristiano will win",
    unreadMessages: 1,
    recentAmount: "450",
    recentCurrency: "USD",
    time: "2:15AM",
    photo: require("../../images/Ker.jpg"),
  },
  {
    id: 5,
    name: "Yongla",
    chat: "This my second number send it here",
    unreadMessages: 11,
    recentAmount: "535",
    recentCurrency: "USD",
    time: "18:01AM",
    photo: require("../../images/keryti.jpg"),
  },
  {
    id: 6,
    name: "Chelsea",
    chat: "Broooooo",
    unreadMessages: 4,
    recentAmount: "100.0",
    recentCurrency: "USD",
    time: "05:30AM",
    photo: require("../../images/chelsea.jpg"),
  },
  {
    id: 7,
    name: "Carine",
    chat: "hehehhe Yosai ah",
    unreadMessages: 2,
    recentAmount: "480",
    recentCurrency: "USD",
    time: "11:18AM",
    photo: require("../../images/rand2.jpg"),
  },
  {
    id: 8,
    name: "Adrien",
    chat: "Yo le ATO ondit quoi nor...",
    unreadMessages: 12,
    recentAmount: "100,100",
    recentCurrency: "NGN",
    time: "15:05AM",
    photo: require("../../images/random.jpg"),
  },
  {
    id: 9,
    name: "ATO",
    chat: "Yo ATO odk nor",
    unreadMessages: 4,
    recentAmount: "15,000",
    recentCurrency: "XAF",
    time: "10:30AM",
    photo: require("../../images/ATO.jpg"),
  },
  {
    id: 10,
    name: "me",
    chat: "Yo ATO odk nor",
    unreadMessages: 4,
    recentAmount: "15,000",
    recentCurrency: "XAF",
    time: "10:30AM",
    photo: require("../../images/ATO.jpg"),
  },
];
