export const conversation = [
  {
    id: 1,
    name: "me",
    chat: "Yo Odk Nor Brolos",
    seen: true,
  },
  {
    id: 2,
    name: "Oliver",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 3,
    name: "me",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 4,
    name: "Oliver",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 5,
    name: "Oliver",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 6,
    name: "me",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 7,
    name: "Oliver",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 8,
    name: "me",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 9,
    name: "me",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 10,
    name: "Oliver",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 11,
    name: "me",
    chat: "Yesailo brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 12,
    name: "Oliver",
    chat: "Yesailo brosolo jasfgasge suis la dosai",
    seen: true,
  },
  {
    id: 13,
    name: "Oliver",
    chat: "asfgasg brosolo je suis la dosai",
    seen: true,
  },
  {
    id: 14,
    name: "me",
    chat: "I am the only brosolo je suis la dosai",
    seen: false,
  },
  {
    id: 15,
    name: "me",
    chat: "I am the shetgh only brosolo je suis la dosai",
    seen: false,
  },
];
